Started by user khalid
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/shopping-app@2
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] deleteDir
[Pipeline] git
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/dilnawaj9128/shopping-app.git
 > git init /var/lib/jenkins/workspace/shopping-app@2 # timeout=10
Fetching upstream changes from https://github.com/dilnawaj9128/shopping-app.git
 > git --version # timeout=10
 > git --version # 'git version 2.53.0'
 > git fetch --tags --force --progress -- https://github.com/dilnawaj9128/shopping-app.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/dilnawaj9128/shopping-app.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision c7ab573760ac107c1e8a027b490b78db08173673 (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c7ab573760ac107c1e8a027b490b78db08173673 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b main c7ab573760ac107c1e8a027b490b78db08173673 # timeout=10
Commit message: "ci: update image tag to 106 [skip ci]"
 > git rev-list --no-walk c7ab573760ac107c1e8a027b490b78db08173673 # timeout=10
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ git log -1 --pretty=%an
[Pipeline] error
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (SonarQube Analysis)
Stage "SonarQube Analysis" skipped due to earlier failure(s)
