pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                deleteDir()
                git branch: 'main', url: 'https://github.com/dilnawaj9128/shopping-app.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=shopping-app \
                        -Dsonar.projectName=shopping-app \
                        -Dsonar.sources=.
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Backend') {
            steps {
                sh 'docker build -t shopping-app-backend:latest ./backend'
            }
        }

        stage('Build Frontend') {
            steps {
                sh 'docker build -t shopping-app-frontend:latest ./frontend'
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                trivy image --exit-code 1 --severity CRITICAL --no-progress shopping-app-backend:latest
                trivy image --exit-code 1 --severity CRITICAL --no-progress shopping-app-frontend:latest
                '''
            }
        }
        stage("Push to Docker Hub") {
            steps {
                echo "Pushing images to Docker Hub"
                withCredentials([usernamePassword(
                    credentialsId: 'dockerHubCred',
                    passwordVariable: 'dockerHubPass',
                    usernameVariable: 'dockerHubUser')]) {
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                    sh "docker image tag shopping-app-backend:latest ${env.dockerHubUser}/shopflow-backend:latest"
                    sh "docker image tag shopping-app-frontend:latest ${env.dockerHubUser}/shopflow-frontend:latest"
                    sh "docker push ${env.dockerHubUser}/shopflow-backend:latest"
                    sh "docker push ${env.dockerHubUser}/shopflow-frontend:latest"
                }
                echo "mages pushed successfully"
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                echo "Deploying to Kubernetes"
                sh """
                    kubectl set image deployment/backend \
                    backend=dilnawaz9128/shopflow-backend:latest \
                    -n shopflow

                    kubectl set image deployment/frontend \
                    frontend=dilnawaz9128/shopflow-frontend:latest \
                    -n shopflow

                    kubectl rollout status deployment/backend -n shopflow --timeout=120s
                    kubectl rollout status deployment/frontend -n shopflow --timeout=120s
                """
                echo "kubernetes deployment successful"
            }
        }
        stage("Smoke Test") {
            steps {
                echo "Testing if app is running"
                sh "sleep 30"
                sh "curl -f http://16.170.216.93:5000/health"
                sh "curl -f http://16.170.216.93:9090"
            }
        }
    }
}
