name: ShopFlow CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-backend:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          target: production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-frontend:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-frontend:latest

      - name: Trivy Scan Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-backend:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Trivy Scan Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/shopflow-frontend:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Update Helm image tag
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/tag: .*/tag: \"${{ env.IMAGE_TAG }}\"/" helm/shopflow/values.yaml
          git config user.email "actions@github.com"
          git config user.name  "GitHub Actions"
          git add helm/shopflow/values.yaml
          git commit -m "ci: bump image to ${{ env.IMAGE_TAG }} [skip ci]" || true
          git push
